services:
  - type: web
    name: ecommerce-backend
    runtime: python
    buildCommand: ""
    startCommand: gunicorn ecommerce.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce.settings
      - key: PYTHON_VERSION
        value: 3.11
    autoDeploy: true